name: flutter_system_proxy
description: A Flutter Plugin to detect System proxy. When using HTTP client that are not proxy aware this plugin can help with finding the proxy from system settings which then can be used with HTTP Client to make a successful request.
homepage: https://github.com/BrowserStackCE/flutter_system_proxy.git
publish_to: https://dart.cloudsmith.io/alkami/flutter/
version: 3.23.0  # Upstream version for this update was 0.1.5

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.24.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  alkami_dart_analysis: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.browserstack.fluttersystemproxy.flutter_system_proxy
        pluginClass: FlutterSystemProxyPlugin
      ios:
        pluginClass: FlutterSystemProxyPlugin

  
