name: flutter_system_proxy
description: A Flutter Plugin to detect System proxy. When using HTTP client that are not proxy aware this plugin can help with finding the proxy from system settings which then can be used with HTTP Client to make a successful request.
homepage: https://github.com/Rushabhshroff/flutter_system_proxy.git
publish_to: https://dart.cloudsmith.io/alkami/flutter/
version: 3.1.0 #Original version when cloned was 0.0.2

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  alkami_core_dependencies: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^3.2.2

  flutter:
    sdk: flutter

dev_dependencies:
  alkami_core_dev_dependencies: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^3.0.0

  alkami_dart_analysis: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^4.0.0

  mplat_pr_tools: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.browserstack.fluttersystemproxy.flutter_system_proxy
        pluginClass: FlutterSystemProxyPlugin
      ios:
        pluginClass: FlutterSystemProxyPlugin

  
