name: Validate PR is Ready for Merge

env:
  dart_version: 2.16.1
  flutter_version: 2.10.3
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
  JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

on:
  pull_request:
    branches:
      - main
      - 'release/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pr_validation:
    name: Validate Pull Request is Ready for Merge
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          global: false
          token: '${{ secrets.GH_ACTIONS_PAT }}'

      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ env.dart_version }}

      - name: Git Config Update
        run: git config --global url."https://x-token-auth:${{ secrets.GH_ACTIONS_PAT }}@github.com".InsteadOf https://github.com

      - name: Authorize Cloudsmith
        run:  ./shell_scripts/authorize_cloudsmith.sh ${{ secrets.CLOUDSMITH_API_KEY }}

      - name: Pub get
        run: dart pub get

      - name: Validate PR is ready
        run: dart pub run mplat_pr_tools validatePRIsReadyForMerge --publishDryRun
