name: Publish

on:
  push:
    branches:
      - main
      - hotfix/**

jobs:
  build:
    name: Publish
    uses: alkami/github_actions/.github/workflows/reusable_publish.yaml@main
    secrets: inherit
