name: Release Package

env:
  dart_version: 2.16.1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  release_package:
    name: Release and tag package with GitHub Api
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: ${{ env.dart_version }}
      
      - name: Authorize Cloudsmith
        run:  ./shell_scripts/authorize_cloudsmith.sh ${{ secrets.CLOUDSMITH_API_KEY }}
      
      - name: Pub get
        run: dart pub get

      - name: Publish
        run: dart pub run mplat_pr_tools publish
